module Graph
export addEdge, create_graph, displayAdjList
using Pkg
# Add if you don't have the package: Pkg.add("DataStructures") 
using DataStructures

function addEdge(adj, u, v) #Add edge from u to v
    push!(adj[u], v)  # Adjusting for 1-based indexing in Julia
end

function displayAdjList(adj)
    for (i, neighbors) in enumerate(adj)
        print("$i: ")
        println(join(neighbors, ", "))
        
    end
end

function create_graph(dir::String)
    junct = 128 #Number of junctions
    if dir == "from"
        from_kh = [Vector{Int}() for _ in 1:junct]  # Initialize adjacancy array from Kh
        # Add edges 
        #from kh
        addEdge(from_kh, 1, 14)
        addEdge(from_kh, 2, 10)
        addEdge(from_kh, 3, 11)
        addEdge(from_kh, 4, 15)
        addEdge(from_kh, 5, 16)
        addEdge(from_kh, 6, 12)
        addEdge(from_kh, 7, 13)
        addEdge(from_kh, 8, 17)
        addEdge(from_kh, 10, 14)
        addEdge(from_kh, 11, 10)
        addEdge(from_kh, 11, 15)
        addEdge(from_kh, 12, 16)
        addEdge(from_kh, 13, 12)
        addEdge(from_kh, 13, 17)
        addEdge(from_kh, 14, 18)
        addEdge(from_kh, 15, 19)
        addEdge(from_kh, 16, 21)
        addEdge(from_kh, 17, 23)
        addEdge(from_kh, 18, 19)
        addEdge(from_kh, 18, 22)
        addEdge(from_kh, 19, 18)
        addEdge(from_kh, 19, 20)
        addEdge(from_kh, 20, 21)
        addEdge(from_kh, 20, 22)
        addEdge(from_kh, 21, 20)
        addEdge(from_kh, 21, 23)
        addEdge(from_kh, 22, 24)
        addEdge(from_kh, 23, 25)
        addEdge(from_kh, 24, 127)
        addEdge(from_kh, 25, 24)
        return from_kh,  1
    elseif dir == "to"
        to_kh = [Vector{Int}() for _ in 1:junct]  # Initialize adjacancy array from Nørreport
        #to kh
        addEdge(to_kh, 128, 25)
        addEdge(to_kh, 25, 23)
        addEdge(to_kh, 23, 21)
        addEdge(to_kh, 21, 16)
        addEdge(to_kh, 16, 5)
        addEdge(to_kh, 16, 12)
        addEdge(to_kh, 12, 6)
        addEdge(to_kh, 12, 13)
        addEdge(to_kh, 13, 7)
        addEdge(to_kh, 23, 17)
        addEdge(to_kh, 17, 8)
        addEdge(to_kh, 17, 13)
        addEdge(to_kh, 21, 20)
        addEdge(to_kh, 20, 19)
        addEdge(to_kh, 19, 15)
        addEdge(to_kh, 19, 18)
        addEdge(to_kh, 15, 4)
        addEdge(to_kh, 15, 11)
        addEdge(to_kh, 11, 3)
        addEdge(to_kh, 18, 14)
        addEdge(to_kh, 14, 10)
        addEdge(to_kh, 10, 2)
        addEdge(to_kh, 10, 11)
        addEdge(to_kh, 14, 1)
        #Implent edges from Valby to Kh
        addEdge(to_kh, 123, 92)
        addEdge(to_kh, 92, 64)
        addEdge(to_kh, 64, 45)
        addEdge(to_kh, 45, 42)
        addEdge(to_kh, 42, 34)
        addEdge(to_kh, 34, 33)
        addEdge(to_kh, 33, 28)
        addEdge(to_kh, 28, 3) 
        addEdge(to_kh, 28, 29)
        addEdge(to_kh, 29, 4)
        addEdge(to_kh, 33, 27)
        addEdge(to_kh, 27, 2)
        addEdge(to_kh, 27, 26)
        addEdge(to_kh, 26, 1)
        addEdge(to_kh, 92, 88)
        addEdge(to_kh, 88, 86)
        addEdge(to_kh, 86, 76)
        addEdge(to_kh, 76, 65)
        addEdge(to_kh, 65, 57)
        addEdge(to_kh, 57, 56)
        addEdge(to_kh, 56, 35)
        addEdge(to_kh, 35, 34)
        addEdge(to_kh, 86, 84)
        addEdge(to_kh, 84, 82)
        addEdge(to_kh, 82, 80)
        addEdge(to_kh, 80, 76)
        addEdge(to_kh, 80, 77)  
        addEdge(to_kh, 77, 66)
        addEdge(to_kh, 66, 60)
        addEdge(to_kh, 60, 53)  
        addEdge(to_kh, 53, 51)
        addEdge(to_kh, 51, 37)
        addEdge(to_kh, 37, 36)
        addEdge(to_kh, 36, 29)
        addEdge(to_kh, 36, 35)
        addEdge(to_kh, 37, 9)
        addEdge(to_kh, 51, 50)
        addEdge(to_kh, 50, 38)
        addEdge(to_kh, 38, 30)
        addEdge(to_kh, 30, 5)
        addEdge(to_kh, 50, 46)
        addEdge(to_kh, 46, 43)
        addEdge(to_kh, 43, 41)
        addEdge(to_kh, 41, 38)
        addEdge(to_kh, 41, 40)
        addEdge(to_kh, 40, 39)
        addEdge(to_kh, 39, 31)
        addEdge(to_kh, 31, 6)
        addEdge(to_kh, 31, 30)
        addEdge(to_kh, 39, 32)
        addEdge(to_kh, 32, 7)
        addEdge(to_kh, 82, 81)
        addEdge(to_kh, 81, 78)
        addEdge(to_kh, 78, 75)
        addEdge(to_kh, 75, 47)
        addEdge(to_kh, 47, 43)
        addEdge(to_kh, 75, 72)
        addEdge(to_kh, 72, 71)
        addEdge(to_kh, 71, 69)
        addEdge(to_kh, 69, 68)
        addEdge(to_kh, 68, 67)
        addEdge(to_kh, 67, 58)
        addEdge(to_kh, 58, 54)
        addEdge(to_kh, 54, 52)
        addEdge(to_kh, 52, 47)
        addEdge(to_kh, 67, 61) 
        addEdge(to_kh, 61, 55)
        addEdge(to_kh, 55, 48)
        addEdge(to_kh, 48, 40)
        addEdge(to_kh, 48, 44)
        addEdge(to_kh, 44, 32)
        addEdge(to_kh, 44, 8)
        addEdge(to_kh, 58, 55)
        addEdge(to_kh, 65, 60)
        addEdge(to_kh, 78, 77)
        

        return to_kh , 2
    else
        println("Error: Invalid direction.")
        println("Try either to or from")
        return nothing
    end
end

end